name: aggregator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python deps
        run: pip install requests

      - name: Download Clash Core
        run: |
          wget https://github.com/Dreamacro/clash/releases/latest/download/clash-linux-amd64.gz
          gunzip clash-linux-amd64.gz
          chmod +x clash-linux-amd64
          mv clash-linux-amd64 clash

      - name: Speed Filter
        run: python speed_filter.py
