name: aggregator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Run Main Script
        run: python main.py

      - name: Commit Output
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add clash.yaml

          git diff --quiet || git commit -m "auto update"

          git push
