name: Collect

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

# 【关键点】全局环境变量只保留时区！
# 彻底删除了 GIST_PAT 和 GIST_LINK，拔掉触发默认爬虫的“电源”
env:
  TZ: Asia/Shanghai

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install
        run: pip3 install -r requirements.txt

      - name: Collect
        # 【关键点】只保留最基础的运行指令和 --skip
        # 没有任何多余参数，脚本只能乖乖去读你的 json 配置文件
        run: python -u subscribe/collect.py --skip

      - name: Timestamp
        run: date
