name: Collect

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install
        run: pip3 install -r requirements.txt

      - name: Collect
        # 【终极杀招】强制指定只加载配置文件，并使用 --skip 跳过所有内置爬虫
        # 即使代码想爬，也会因为找不到指令而停止
        run: python -u subscribe/collect.py --skip --source subscribe/config/config.default.json

      - name: Timestamp
        run: date
